export const timelines = [
	{
		id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
		type: "experience",
		title: "Full-Stack Software Engineer",
		organization: "Chemmin Co., Ltd.",
		description:
			"Developing a software (Web application) with a strong focus on trading business application includes sales & marketing, procurement, logistics, warehouses at every stage of development. Utilizing reliable tools and self-designed some core business functionalities for developing a software. Proficiently manage web development projects using Python, JavaScript and TypeScript, incorporating cutting-edge with front-end frameworks (Quasar - The enterprise-ready cross-platform Vue.js framework, Next.js - The React framework for the web development) and back-end framworks (Node.js and Django REST Framework) with seamless database integration with PosgreSQL and MongoDB to deliver high-quality web application.",

		started_at: "2019-06-01",
		ended_at: "2024-01-01",
		isCurrent: true,
		responsibilities: [
			"Proficient in Next.js, React, TailwindCSS, Vue.js, Quasar framework to create responsive websites both single page applications and server-side rendering application.",
			"Develop REST APIs with Node.js (Express.js), Next.js API Route handlers and Django REST framework to facilitate communication between front-end and back-end.",
			"Integration to third party API services to enhance efficiency and smooth data integration.",
			"Translated trading business requirements into precise technical specifications, bridging the gap between client needs and development outcomes.",
			"Effectively managed a team of 2 - 3 members, fostering collaboration and driving successful project delivery.",
			"Demonstrated ability to effectively communicate with cross-cultural teams, ensuring seamless progress updates and collaboration.",
		],
		skills: ["Full-Stack Development"],
	},
	{
		id: "110e8400-e29b-11d4-a716-446655440000",
		type: "experience",
		title: "Technical Sales Representatve Food Section",
		organization: "Chemmin Co., Ltd.",
		description: "Chemmin Corporation is one of the leading importers and distributors of chemical industries to serve in various industries including basic polymer, food industry, ceramic industry, and general chemical.",

		started_at: "2018-01-01",
		ended_at: "2019-12-31",
		isCurrent: false,
		responsibilities: ["Developing new products, customers and sales transactions.", "Maintains the existing foods & beverages and ceramic customers.", "Maintains the existing sales transaction handled for promoting positive relation with customers.", "Participates in business development team’s activities in order to achieve sales targets.", "Performs miscellaneous job-related duties as assigned."],
		skills: ["Sales & Marketing"],
	},
	{
		id: "61c35085-72d7-42b4-8d62-738f700d4b92",
		type: "experience",
		title: "Food Safety Specialist Trainee",
		organization: "Ecolab Co., Ltd.",
		description: "Ecolab is the global leader in water, hygiene and energy technologies and services. Around the world businesses in foodservice, food processing, hospitality, healthcare, industrial, and oil and gas markets choose Ecolab products and services to keep their environment clean and safe, operate efficiently and achieve sustainability goals.",
		started_at: "2017-01-01",
		ended_at: "2017-04-30",
		isCurrent: false,
		responsibilities: [],
		skills: ["Food Safety"],
	},
	{
		id: "8f7b5db9-d935-4e42-8e05-1f1d0a3dfb97",
		type: "education",
		title: "Bachelor of Science (B.Sc.), Food Science and Technology 1st Class Honors",
		organization: "Mae Fah Luang University",
		description: "Grade: 3.69",
		started_at: "2013-01-01",
		ended_at: "2017-12-31",
		isCurrent: false,
		responsibilities: [],
		skills: ["Food Science and Technology"],
	},
	{
		id: "8f7b5db9-d935-4e42-8e05-1f1d0a3dfb96",
		type: "education",
		title: "Math & Science",
		organization: "Watsuthiwararam School",
		description: "Grade: 3.80",
		started_at: "2008-01-01",
		ended_at: "2013-12-31",
		isCurrent: false,
		responsibilities: [],
		skills: ["Mathematics", "Science"],
	},
	{
		id: "1f0f2c02-e299-40de-9b1d-86ef9e42126b",
		type: "education",
		title: "Secondary School",
		organization: "Sarasas Witead Suksa School",
		description: "Grade: 3.92",
		started_at: "2007-12-31",
		ended_at: "2000-01-01",
		isCurrent: false,
		responsibilities: [],
		skills: [],
	},
];

export type Timeline = (typeof timelines)[number];
